### ISSUE TITLE
Some intructions

### ISSUE THREAD

**Issue by yuhanggao** [P-J-Y/SErup#2]
1. hek中提取的CME的信息（时间和位置），取出StartTime前30min的AR图像
方法：记CE_T=CEresult['hek']['event_starttime'][0]
将AR的 [tstart, tend]取为[CE_T-40min, CE_T-20min]

2. 选出对应该CME的AR——
对于每个AR，给出一个DeltaT=CEresult['hek']['event_starttime'][0]-ARresult['hek']['event_starttime'][0]
得到CEresult['hek']['event_event_coord2'][0]对应的较差自转速度V（https://docs.sunpy.org/en/stable/generated/gallery/plotting/simple_differential_rotation.html?highlight=differential%20rotation）
计算距离：dist=np.sqrt((AR_x-(CE_x-V*DeltaT))**2+(AR_y-CE_y))**2)
选出最小距离对应的AR
(要不要加一个判据，比如AR_y-CE_y<1 ?)

3. 画出AR的图，和(CE_x-V*DeltaT, CE_y)处的图像，进行对比，检查我们选出来的AR是否有效。
对于AR好像有area_raw这个关键词可以用，单位是km2，但是似乎有的有面积，有些没有

**Comment by P-J-Y** [comment]
这些已经完成了：
1、getDateset.py可以下图片
2、3、 match的功能已经实现了
4、多波段简单，直接多写几个仪器就行
